//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 5:52:19 PM on Thursday, March 04, 2004
//
//	Generated for file: MiniADPCM.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniADPCM"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainStartButton                           1001	//(Left Origin = 35, Top Origin = 47, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainStopButton                            1002	//(Left Origin = 35, Top Origin = 107, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainFileButton                            1003	//(Left Origin = 35, Top Origin = 17, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainRecordButton                          1004	//(Left Origin = 35, Top Origin = 77, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainVolumeFeedbackSliderControl           1005	//(Left Origin = 15, Top Origin = 134, Width = 128, Height = 15, Usable = 1, Initial Value = 1024, Minimum Value = 0, Maximum Value = 2048, Page Jump Amount = 256, Thumb Bitmap = 0, Background Bitmap = 0)

#define OptionsAbout							  1000

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define NoCPMLibAlert                             1000
#define NoCPMLibOK                                0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0

//	Resource: Talt 1200
#define InfoAlert                                 1200
#define InfoOK                                    0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

