//	Header generated by Constructor for Palm OS (R) 1.6.2
//
//	Generated at 2:06:57 PM on Tuesday, April 02, 2002
//
//	Generated for file: C:\AS\Software\Hemingway\Sources\SDK\examples\Example E - WritePad - Graphic\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		""
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainUnnamed1001Label                      1001	//(Left Origin = 23, Top Origin = 34, Usable = 1, Font = Bold)
#define MainUnnamed1002Label                      1002	//(Left Origin = 48, Top Origin = 58, Usable = 1, Font = Standard)
#define MainUnnamed1003Label                      1003	//(Left Origin = 48, Top Origin = 106, Usable = 1, Font = Standard)
#define MainMinLabel                              1004	//(Left Origin = 61, Top Origin = 118, Usable = 0, Font = Standard)
#define MainMaxLabel                              1005	//(Left Origin = 61, Top Origin = 131, Usable = 0, Font = Standard)
#define MainLeftLabel                             1006	//(Left Origin = 61, Top Origin = 84, Usable = 0, Font = Standard)
#define MainRightLabel                            1007	//(Left Origin = 61, Top Origin = 70, Usable = 0, Font = Standard)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define WritePadExtNotFoundAlert                  1000
#define WritePadExtNotFoundOK                     0

//	Resource: Talt 1100
#define WritePadDrawErrorAlert                    1100
#define WritePadDrawErrorOK                       0


//	Resource: MBAR 1000
#define AboutFormMenuBar                          1000


//	Resource: MENU 1100
#define MainOptionsMenu                           1100
#define MainOptionsAboutStarter                   1100


//	Resource: PICT 1204
#define Graphic4Bitmap                            1204

//	Resource: PICT 1203
#define Graphic3Bitmap                            1203

//	Resource: PICT 1000
#define BigIconBitmap                             1000

//	Resource: PICT 1201
#define Graphic1Bitmap                            1201

//	Resource: PICT 1202
#define Graphic2Bitmap                            1202

