#ifndef MINICAMERARSC_H
#define MINICAMERARSC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 11:06:33 AM on Monday, May 22, 2006
//
//	Generated for file: MiniCamera.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniCamera"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainBackButton                            1003	//(Left Origin = 1, Top Origin = 132, Width = 16, Height = 27, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Symbol)
#define MainAdvancedButton                        1006	//(Left Origin = 40, Top Origin = 132, Width = 52, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainLightButton                           1012	//(Left Origin = 95, Top Origin = 132, Width = 48, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainWhiteButton                           1013	//(Left Origin = 1, Top Origin = 147, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainEffectsButton                         1014	//(Left Origin = 95, Top Origin = 147, Width = 48, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainPreviewOnButton                       1015	//(Left Origin = 1, Top Origin = 132, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainSizeButton                            1016	//(Left Origin = 40, Top Origin = 147, Width = 52, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainQueryButton                           1020	//(Left Origin = 21, Top Origin = 147, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainMain2Button                           1032	//(Left Origin = 146, Top Origin = 132, Width = 13, Height = 27, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Symbol)
#define MainZoomButton                            1033	//(Left Origin = 21, Top Origin = 132, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainStreamButton                          1036	//(Left Origin = 60, Top Origin = 132, Width = 46, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainStartStreamButton                     1044	//(Left Origin = 123, Top Origin = 132, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainStopStreamButton                      1045	//(Left Origin = 123, Top Origin = 147, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainAutoWBCheckbox                        1021	//(Left Origin = 105, Top Origin = 134, Width = 55, Height = 12, Usable = 0, Selected = 1, Group ID = 2, Font = Standard)
#define MainFluorescentCheckbox                   1022	//(Left Origin = 33, Top Origin = 147, Width = 64, Height = 12, Usable = 0, Selected = 0, Group ID = 2, Font = Standard)
#define MainIncandescentCheckbox                  1023	//(Left Origin = 33, Top Origin = 134, Width = 70, Height = 12, Usable = 0, Selected = 0, Group ID = 2, Font = Standard)
#define MainSunlightCheckbox                      1024	//(Left Origin = 105, Top Origin = 147, Width = 55, Height = 12, Usable = 0, Selected = 0, Group ID = 2, Font = Standard)
#define MainNormalLightCheckbox                   1025	//(Left Origin = 44, Top Origin = 141, Width = 55, Height = 12, Usable = 0, Selected = 1, Group ID = 3, Font = Standard)
#define MainLowLightCheckbox                      1026	//(Left Origin = 103, Top Origin = 141, Width = 55, Height = 12, Usable = 0, Selected = 0, Group ID = 3, Font = Standard)
#define MainNormalCheckbox                        1027	//(Left Origin = 43, Top Origin = 132, Width = 55, Height = 12, Usable = 0, Selected = 1, Group ID = 4, Font = Standard)
#define MainBWCheckbox                            1028	//(Left Origin = 23, Top Origin = 146, Width = 40, Height = 12, Usable = 0, Selected = 0, Group ID = 4, Font = Standard)
#define MainSepiaCheckbox                         1029	//(Left Origin = 100, Top Origin = 132, Width = 44, Height = 12, Usable = 0, Selected = 0, Group ID = 4, Font = Standard)
#define MainBlueCheckbox                          1030	//(Left Origin = 123, Top Origin = 146, Width = 36, Height = 12, Usable = 0, Selected = 0, Group ID = 4, Font = Standard)
#define MainNegativeCheckbox                      1031	//(Left Origin = 65, Top Origin = 146, Width = 55, Height = 12, Usable = 0, Selected = 0, Group ID = 4, Font = Standard)
#define MainPanelTitleField                       1011	//(Left Origin = 0, Top Origin = 120, Width = 160, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainContrastLabel                         1001	//(Left Origin = 26, Top Origin = 135, Usable = 0, Font = Bold)
#define MainExposureLabel                         1007	//(Left Origin = 27, Top Origin = 148, Usable = 0, Font = Bold)
#define MainSaturationLabel                       1008	//(Left Origin = 92, Top Origin = 135, Usable = 0, Font = Bold)
#define MainSharpnessLabel                        1009	//(Left Origin = 92, Top Origin = 148, Usable = 0, Font = Bold)
#define MainCaptureFormatList                     1017	//(Left Origin = 94, Top Origin = 125, Width = 50, Usable = 0, Font = Standard, Visible Items = 3)
#define MainCaptureSizeList                       1018	//(Left Origin = 35, Top Origin = 125, Width = 40, Usable = 0, Font = Standard, Visible Items = 3)
#define MainStreamList                            1041	//(Left Origin = 21, Top Origin = 125, Width = 40, Usable = 0, Font = Standard, Visible Items = 3)
#define MainStreamFormatList                      1043	//(Left Origin = 20, Top Origin = 125, Width = 60, Usable = 0, Font = Standard, Visible Items = 3)
#define MainStreamPopTrigger                      1040	//(Left Origin = 20, Top Origin = 147, Width = 45, Height = 12, Usable = 0, Anchor Left = 1, Font = Standard, List ID = 1041)
#define MainStreamFormatPopTrigger                1042	//(Left Origin = 20, Top Origin = 134, Width = 55, Height = 12, Usable = 0, Anchor Left = 1, Font = Standard, List ID = 1043)
#define MainCaptureSizePopTrigger                 1048	//(Left Origin = 33, Top Origin = 140, Width = 45, Height = 12, Usable = 0, Anchor Left = 1, Font = Standard, List ID = 1018)
#define MainCaptureFormatPopTrigger               1049	//(Left Origin = 92, Top Origin = 140, Width = 55, Height = 12, Usable = 0, Anchor Left = 1, Font = Standard, List ID = 1017)
#define MainZoomSliderControl                     1046	//(Left Origin = 33, Top Origin = 138, Width = 114, Height = 15, Usable = 0, Initial Value = 0, Minimum Value = 0, Maximum Value = 150, Page Jump Amount = 10, Thumb Bitmap = 1100, Background Bitmap = 1000)
#define MainExposureFeedbackSliderControl         1002	//(Left Origin = 40, Top Origin = 150, Width = 40, Height = 8, Usable = 0, Initial Value = 2, Minimum Value = 0, Maximum Value = 4, Page Jump Amount = 1, Thumb Bitmap = 1100, Background Bitmap = 1000)
#define MainSharpnessFeedbackSliderControl        1004	//(Left Origin = 117, Top Origin = 150, Width = 40, Height = 8, Usable = 0, Initial Value = 2, Minimum Value = 0, Maximum Value = 4, Page Jump Amount = 1, Thumb Bitmap = 1100, Background Bitmap = 1000)
#define MainSaturationFeedbackSliderControl       1005	//(Left Origin = 117, Top Origin = 137, Width = 40, Height = 8, Usable = 0, Initial Value = 2, Minimum Value = 0, Maximum Value = 4, Page Jump Amount = 1, Thumb Bitmap = 1100, Background Bitmap = 1000)
#define MainContrastFeedbackSliderControl         1010	//(Left Origin = 40, Top Origin = 137, Width = 40, Height = 8, Usable = 0, Initial Value = 2, Minimum Value = 0, Maximum Value = 4, Page Jump Amount = 1, Thumb Bitmap = 1100, Background Bitmap = 1000)
#define MainOptionsMenu							  1050
#define OptionsAbout							  1051
#define MainGroupID                               2
#define MainGroupID2                              3
#define MainGroupID3                              4

//	Resource: tFRM 1100
#define DisplayForm                               1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)

//	Resource: tFRM 1200
#define SavingForm                                1200	//(Left Origin = 40, Top Origin = 70, Width = 80, Height = 30, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SavingUnnamed1201Label                    1201	//(Left Origin = 20, Top Origin = 8, Usable = 1, Font = Bold 12)

//	Resource: tFRM 1300
#define QueryForm                                 1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define QueryOKButton                             1317	//(Left Origin = 11, Top Origin = 143, Width = 39, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define QueryCValueField                          1304	//(Left Origin = 56, Top Origin = 16, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryEValueField                          1310	//(Left Origin = 56, Top Origin = 32, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryZValueField                          1311	//(Left Origin = 56, Top Origin = 48, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryLValueField                          1312	//(Left Origin = 56, Top Origin = 128, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QuerySValueField                          1313	//(Left Origin = 56, Top Origin = 64, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryShValueField                         1314	//(Left Origin = 56, Top Origin = 80, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryEfValueField                         1315	//(Left Origin = 56, Top Origin = 96, Width = 32, Height = 14, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryWValueField                          1316	//(Left Origin = 56, Top Origin = 112, Width = 32, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryCMinField                            1321	//(Left Origin = 104, Top Origin = 16, Width = 24, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryCMaxField                            1322	//(Left Origin = 136, Top Origin = 16, Width = 22, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryEMinField                            1323	//(Left Origin = 104, Top Origin = 32, Width = 24, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryZMinField                            1324	//(Left Origin = 104, Top Origin = 48, Width = 24, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QuerySMinField                            1326	//(Left Origin = 104, Top Origin = 64, Width = 24, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryShMinField                           1327	//(Left Origin = 104, Top Origin = 80, Width = 24, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryZMaxField                            1330	//(Left Origin = 136, Top Origin = 48, Width = 22, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryEMaxField                            1332	//(Left Origin = 136, Top Origin = 31, Width = 22, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QuerySMaxField                            1333	//(Left Origin = 136, Top Origin = 64, Width = 22, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryShMaxField                           1334	//(Left Origin = 136, Top Origin = 80, Width = 22, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define QueryContrastLabel                        1301	//(Left Origin = 11, Top Origin = 16, Usable = 1, Font = Standard)
#define QueryExposureLabel                        1302	//(Left Origin = 11, Top Origin = 32, Usable = 1, Font = Standard)
#define QueryZoomLabel                            1303	//(Left Origin = 24, Top Origin = 48, Usable = 1, Font = Standard)
#define QueryLightLabel                           1305	//(Left Origin = 24, Top Origin = 128, Usable = 1, Font = Standard)
#define QuerySaturationLabel                      1306	//(Left Origin = 2, Top Origin = 63, Usable = 1, Font = Standard)
#define QuerySharpnessLabel                       1307	//(Left Origin = 5, Top Origin = 81, Usable = 1, Font = Standard)
#define QueryEffectsLabel                         1308	//(Left Origin = 17, Top Origin = 97, Usable = 1, Font = Standard)
#define QueryWhiteLabel                           1309	//(Left Origin = 21, Top Origin = 112, Usable = 1, Font = Standard)
#define QueryValueLabel                           1318	//(Left Origin = 63, Top Origin = 1, Usable = 1, Font = Standard)
#define QueryMinLabel                             1319	//(Left Origin = 112, Top Origin = 2, Usable = 1, Font = Standard)
#define QueryMaxLabel                             1320	//(Left Origin = 141, Top Origin = 2, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0

//	Resource: Talt 1200
#define InfoAlert                                 1200
#define InfoOK                                    0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 4001
#define BitmapID4001Bitmap                        4001

//	Resource: PICT 5004
#define BitmapID5004Bitmap                        5004

//	Resource: PICT 5006
#define BitmapID5006Bitmap                        5006

//	Resource: PICT 4002
#define BitmapID4002Bitmap                        4002


//	Resource: tbmf 1000
#define SliderBitmapFamily                        1000

//	Resource: tbmf 1100
#define ThumbBitmapFamily                         1100


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001


#endif // MINICAMERARSC_H
