#ifndef FOTOFINISHRSC_H
#define FOTOFINISHRSC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 4:34:18 PM on Tuesday, March 07, 2006
//
//	Generated for file: FotoFinish.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"FotoFinish"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainUnnamed1007BitMap                     2200
#define MainOpenGraphicButton                     1002
#define MainAddTextPushButton                     1001
#define MainPanningPushButton                     1003
#define MainStraightLinePushButton                1004
#define MainFreeLinePushButton                    1005
#define MainTimestampPushButton                   1006
#define MainGroupID                               1

//	Resource: tFRM 1100
#define DetailsForm                               1100
#define DetailsDoneButton                         1104
#define DetailsBackButton                         1105
#define DetailsNextButton                         1106
#define DetailsEditButton                         1117
#define DetailsSaveButton                         1118
#define DetailsCancelButton                       1119
#define DetailsNameField                          1110
#define DetailsSizeField                          1111
#define DetailsResolutionField                    1112
#define DetailsNotesField                         1114
#define DetailsDateField                          1116
#define DetailsUnnamed1103Label                   1103
#define DetailsNameTagLabel                       1107
#define DetailsSizeTagLabel                       1108
#define DetailsResTagLabel                        1109
#define DetailsNotesTagLabel                      1113
#define DetailsDateTagLabel                       1115
#define DetailsImageIndexLabel                    1120
#define DetailsAlbumList                          1101
#define DetailsAlbumListPopTrigger                1102

//	Resource: tFRM 1600
#define AboutForm                                 1600
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1601BitMap                    3000
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603
#define AboutUnnamed1605Label                     1605

//	Resource: tFRM 1700
#define SavePhotoForm                             1700
#define SavePhotoDoneButton                       1706
#define SavePhotoCancelButton                     1707
#define SavePhotoFileNameField                    1702
#define SavePhotoFileNameTagLabel                 1701
#define SavePhotoSaveToTagLabel                   1703
#define SavePhotoAlbumList                        1704
#define SavePhotoAlbumListPopTrigger              1705

//	Resource: tFRM 1800
#define AddTextForm                               1800
#define AddTextDoneButton                         1801
#define AddTextCancelButton                       1802
#define AddTextTextField                          1803
#define AddTextUnnamed1804Label                   1804

//	Resource: tFRM 1900
#define PleaseWaitForm                            1900
#define PleaseWaitPleaseWaitLabel                 1901

//	Resource: tFRM 2000
#define AlbumOrganiseForm                         2000
#define AlbumOrganiseRenameAlbumButton            2002
#define AlbumOrganiseDeleteAlbumButton            2003
#define AlbumOrganiseNewAlbumButton               2004
#define AlbumOrganiseDoneButton                   2005
#define AlbumOrganiseAlbumList                    2001

//	Resource: tFRM 2100
#define AlbumNameForm                             2100
#define AlbumNameDoneButton                       2103
#define AlbumNameCancelButton                     2104
#define AlbumNameAlbumField                       2102
#define AlbumNameUnnamed2101Label                 2101


//	Resource: Talt 1000
#define AlbumInitAlert                            1000
#define AlbumInitOK                               0

//	Resource: Talt 1100
#define DrawErrorAlert                            1100
#define DrawErrorOK                               0

//	Resource: Talt 1200
#define RenameAlbumErrorAlert                     1200
#define RenameAlbumErrorOK                        0

//	Resource: Talt 1300
#define DeleteAlbumErrorAlert                     1300
#define DeleteAlbumErrorOK                        0
#define DeleteAlbumAlert                          2400

//	Resource: Talt 1500
#define SelectionErrorAlert                       1500
#define SelectionErrorOK                          0

//	Resource: Talt 1600
#define PickAlbumFirstErrorAlert                  1600
#define PickAlbumFirstErrorOK                     0

//	Resource: Talt 1800
#define DeleteConfirmAlert                        1800
#define DeleteConfirmYes                          0
#define DeleteConfirmNo                           1

//	Resource: Talt 1900
#define PickFileNameFirstErrorAlert               1900
#define PickFileNameFirstErrorOK                  0

//	Resource: Talt 2000
#define PhotoLibErrorAlert                        2000
#define PhotoLibErrorOK                           0

//	Resource: Talt 2100
#define MoveToUnfiledAlert                        2100
#define MoveToUnfiledYes                          0
#define MoveToUnfiledNo                           1

//	Resource: Talt 1400
#define ImageExistErrorAlert                      1400
#define ImageExistErrorOK                         0

//	Resource: Talt 1700
#define OutOfMemoryErrorAlert                     1700
#define OutOfMemoryErrorOK                        0


//	Resource: MBAR 2000
#define MenuBarID2000MenuBar                      2000


//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutFotoFinish                       1100

//	Resource: MENU 1000
#define FileMenu                                  1000
#define FileNew                                   1000
#define FileOpen                                  1001
#define FileSaveAs                                1002
#define FilePhotoDetails                          1004
#define FileAlbums                                1005

//	Resource: MENU 1300
#define EditMenu                                  1300
#define EditUndo                                  1300
#define EditRedo                                  1301


//	Resource: PICT 3001
#define BitmapID3001Bitmap                        3001

//	Resource: PICT 1001
#define BitmapID1002Bitmap                        1001

//	Resource: PICT 1101
#define BitmapID1004Bitmap                        1101

//	Resource: PICT 1008
#define UnselectedStraightLineBitmap              1008

//	Resource: PICT 1108
#define SelectedStraightLineBitmap                1108

//	Resource: PICT 1208
#define BitmapID1208Bitmap                        1208

//	Resource: PICT 1308
#define BitmapID1308Bitmap                        1308

//	Resource: PICT 1301
#define BitmapID1301Bitmap                        1301

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1401
#define BitmapID1401Bitmap                        1401

//	Resource: PICT 1408
#define BitmapID1408Bitmap                        1408

//	Resource: PICT 1501
#define BitmapID1501Bitmap                        1501

//	Resource: PICT 1508
#define BitmapID1508Bitmap                        1508

//	Resource: PICT 1601
#define BitmapID1601Bitmap                        1601

//	Resource: PICT 1608
#define BitmapID1608Bitmap                        1608

//	Resource: PICT 1701
#define BitmapID1701Bitmap                        1701

//	Resource: PICT 1708
#define BitmapID1708Bitmap                        1708

//	Resource: PICT 1801
#define BitmapID1801Bitmap                        1801

//	Resource: PICT 1808
#define BitmapID1808Bitmap                        1808

//	Resource: PICT 1901
#define BitmapID1901Bitmap                        1901

//	Resource: PICT 1908
#define BitmapID1908Bitmap                        1908

//	Resource: PICT 2001
#define BitmapID2001Bitmap                        2001

//	Resource: PICT 2008
#define BitmapID2008Bitmap                        2008

//	Resource: PICT 2101
#define BitmapID2101Bitmap                        2101

//	Resource: PICT 2108
#define BitmapID2108Bitmap                        2108

//	Resource: PICT 3008
#define BitmapID3008Bitmap                        3008

//	Resource: PICT 2201
#define BitmapID2201Bitmap                        2201

//	Resource: PICT 2208
#define BitmapID2208Bitmap                        2208

//	Resource: PICT 3018
#define BitmapID3018Bitmap                        3018

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1218
#define BitmapID1218Bitmap                        1218

//	Resource: PICT 1318
#define BitmapID1318Bitmap                        1318

//	Resource: PICT 1418
#define BitmapID1418Bitmap                        1418

//	Resource: PICT 1518
#define BitmapID1518Bitmap                        1518

//	Resource: PICT 1618
#define BitmapID1618Bitmap                        1618

//	Resource: PICT 1718
#define BitmapID1718Bitmap                        1718

//	Resource: PICT 1818
#define BitmapID1818Bitmap                        1818

//	Resource: PICT 1918
#define BitmapID1918Bitmap                        1918

//	Resource: PICT 2018
#define BitmapID2018Bitmap                        2018

//	Resource: PICT 2118
#define BitmapID2118Bitmap                        2118

//	Resource: PICT 2218
#define BitmapID2218Bitmap                        2218


//	Resource: tbmf 2000
#define OpenUnselectedBitmapFamily                2000

//	Resource: tbmf 1900
#define PanningSelectedBitmapFamily               1900

//	Resource: tbmf 1800
#define PanningUnselectedBitmapFamily             1800

//	Resource: tbmf 1700
#define TimestampSelectedBitmapFamily             1700

//	Resource: tbmf 1600
#define TimestampUnselectedBitmapFamily           1600

//	Resource: tbmf 1500
#define AddTextSelectedBitmapFamily               1500

//	Resource: tbmf 1400
#define AddTextUnselectedBitmapFamily             1400

//	Resource: tbmf 1300
#define CurvyLineUnselectedBitmapFamily           1300

//	Resource: tbmf 1200
#define CurvyLineSelectedBitmapFamily             1200

//	Resource: tbmf 1100
#define StraightLineSelectedBitmapFamily          1100

//	Resource: tbmf 1000
#define StraightLineUnselectedBitmapFamily        1000

//	Resource: tbmf 2100
#define OpenSelectedBitmapFamily                  2100

//	Resource: tbmf 3000
#define AboutBoxBitmapFamily                      3000

//	Resource: tbmf 2200
#define ColorPaletteBitmapFamily                  2200


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000


#endif // FOTOFINISHRSC_H
