/***************************************************************************************
*	Header generated by Constructor for Palm OS (R) 1.6.2
*
*	Generated at 11:21:12 PM on Monday, April 05, 2004
*
*	Generated for file: C:\Dev\HtmlLibTest68K\Rsc\HtmlLibTest.rsrc
*
*	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
*	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
*
*	Palm App Name:   		"HTMLLibTest"
*
*	Palm App Version:		"1.1" 
****************************************************************************************/



/*	Resource: tFRM 1000 */
#define MainForm                                  1000	/*(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0) */
#define MainRenderButton                          1002	/*(Left Origin = 94, Top Origin = 139, Width = 58, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard) */
#define MainContentField                          1001	/*(Left Origin = 6, Top Origin = 20, Width = 150, Height = 115, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 2000, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0) */
#define MainTestPageList                          1003	/*(Left Origin = 18, Top Origin = 134, Width = 40, Usable = 0, Font = Standard, Visible Items = 2) */
#define MainTestPagePopTrigger                    1004	/*(Left Origin = 5, Top Origin = 139, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1003) */

/*	Resource: tFRM 1100 */
#define AboutForm                                 1100	/*(Left Origin = 2, Top Origin = 78, Width = 156, Height = 80, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0) */
#define AboutOKButton                             1103	/*(Left Origin = 5, Top Origin = 60, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard) */
#define AboutAccessBitMap                         1500	/*(Left Origin = 5, Top Origin = 21, Bitmap Resource ID = 1500, Usable = 1) */
#define AboutUnnamed1102Label                     1102	/*(Left Origin = 5, Top Origin = 41, Usable = 1, Font = Standard) */

/*	Resource: tFRM 1200 */
#define RenderForm                                1200	/*(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0) */
#define RenderDoneButton                          1201	/*(Left Origin = 5, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard) */
#define RenderScroll0ScrollBar                    1202	/*(Left Origin = 5, Top Origin = 24, Width = 7, Height = 100, Usable = 0, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0) */
#define RenderScroll1ScrollBar                    1203	/*(Left Origin = 20, Top Origin = 24, Width = 7, Height = 100, Usable = 0, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0) */
#define RenderScroll2ScrollBar                    1204	/*(Left Origin = 35, Top Origin = 24, Width = 7, Height = 100, Usable = 0, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0) */
#define RenderScroll3ScrollBar                    1205	/*(Left Origin = 50, Top Origin = 24, Width = 7, Height = 100, Usable = 0, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0) */
#define RenderScroll4ScrollBar                    1206	/*(Left Origin = 65, Top Origin = 24, Width = 7, Height = 100, Usable = 0, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0) */
#define RenderScroll5ScrollBar                    1207	/*(Left Origin = 80, Top Origin = 24, Width = 7, Height = 100, Usable = 0, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0) */

/*	Resource: tFRM 1500 */
#define FindForm                                  1500	/*(Left Origin = 2, Top Origin = 67, Width = 156, Height = 91, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 10000, Default Button ID = 0) */
#define FindFindButton                            1502	/*(Left Origin = 5, Top Origin = 74, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard) */
#define FindCancelButton                          1503	/*(Left Origin = 47, Top Origin = 74, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard) */
#define FindWrapCheckbox                          1501	/*(Left Origin = 5, Top Origin = 55, Width = 85, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Bold) */
#define FindFindField                             1505	/*(Left Origin = 22, Top Origin = 36, Width = 129, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0) */
#define FindGSIGraffitiShift                      1506	/*(Left Origin = 142, Top Origin = 78) */
#define FindFindLabel                             1504	/*(Left Origin = 7, Top Origin = 21, Usable = 1, Font = Bold) */


/*	Resource: Talt 1200 */
#define SelectedTextAlert                         1200
#define SelectedTextOK                            0

/*	Resource: Talt 1100 */
#define NoSelectedTextAlert                       1100
#define NoSelectedTextOK                          0

/*	Resource: Talt 1000 */
#define LinkSelectAlert                           1000
#define LinkSelectOK                              0

/*	Resource: Talt 2400 */
#define TextNotFoundAlert                         2400
#define TextNotFoundOK                            0
 
/*	Resource: Talt 1400 */
#define ImageNotFoundAlert                        1400
#define ImageNotFoundOK                           0

/*	Resource: Talt 1700 */
#define ImageSizeErrAlert						  1700
#define ImageReadErrOK							  0

/*	Resource: Talt 1800 */
#define MemoryAllocateErr						  1800
#define MemoryAllocateOK						  0

/*	Resource: Talt 1900 */
#define ImageRenderErr							  1900
#define ImageRenderOK							  0

/*	Resource: Talt 1850 */
#define FileReadErr								  1850
#define FileReadOK								  0

/*	Resource: Talt 1300 */
#define SubmitFormAlert                           1300
#define SubmitFormOK                              0


/*	Resource: MBAR 1000 */
#define MainMenuBar                               1000

/*	Resource: MBAR 1100 */
#define RenderMenuBar                             1100


/*	Resource: MENU 1000 */
#define OptionsMenu                               1000
#define OptionsAboutHtmlLibTest                   1000

/*	Resource: MENU 1100 */
#define PageMenu                                  1100
#define PageFindTextOnPage                        1100
#define PageGetTextSelection                      1101
#define PageWideDisplay                           1102
#define PageNarrowDisplay                         1103
#define PageResizeScreen                          1104

/*	Resource: MENU 10000 */
#define EditMenu                                  10000
#define EditUndo                                  10000	/*  Command Key: U */
#define EditCut                                   10001	/*  Command Key: X */
#define EditCopy                                  10002	/*  Command Key: C */
#define EditPaste                                 10003	/*  Command Key: P */
#define EditSelectAll                             10004	/*  Command Key: S */
#define EditKeyboard                              10006	/*  Command Key: K */
#define EditGraffitiHelp                          10007	/*  Command Key: G */


/*	Resource: tSTR 1100 */
#define Test2String                               1100	// "<html><head><title>Test2</title></head><body>There is an image below this paragraph of text.<br><img src="smile.jpg" alt="smile"><br><form action="post.html">T1:<input name="t1"><br><input type="submit" name="submit"></form></body></html>" */

/*	Resource: tSTR 1000 */
#define Test1String                               1000	// "<html><body><h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><p>Test Scan phone number 510-555-1212</p><p><a href="http://www.google.com">One</a><br><a href="http://www.yahoo.com">Two</a><br><a href="http://www.cnn.com">Three</a></p></body></html>" */


/*	Resource: PICT 1503 */
#define AccessLogohighBitmap                      1503

/*	Resource: PICT 1501 */
#define AccessLogolowBitmap                       1501

/*	Resource: PICT 1000 */
#define SmileBitmap                               1000


/*	Resource: tbmf 1000 */
#define SmileBitmapFamily                         1000

/*	Resource: tbmf 1500 */
#define AccessLogoBitmapFamily                    1500

