//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 3:51:15 PM on Wednesday, January 05, 2005
//
//	Generated for file: MiniBuzzer.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniBuzzer"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainPlayButton                            1002	//(Left Origin = 35, Top Origin = 87, Width = 43, Height = 26, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainFileButton                            1003	//(Left Origin = 34, Top Origin = 26, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainStopPButton                           1009	//(Left Origin = 35, Top Origin = 87, Width = 43, Height = 26, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainRecordButton                          1010	//(Left Origin = 87, Top Origin = 87, Width = 43, Height = 26, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainStopRButton                           1011	//(Left Origin = 87, Top Origin = 87, Width = 43, Height = 26, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainFileField                             1006	//(Left Origin = 29, Top Origin = 52, Width = 120, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTypeField                             1008	//(Left Origin = 35, Top Origin = 67, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1001Label                      1001	//(Left Origin = 62, Top Origin = 120, Usable = 1, Font = Bold)
#define MainUnnamed1004Label                      1004	//(Left Origin = 8, Top Origin = 52, Usable = 1, Font = Bold)
#define MainUnnamed1007Label                      1007	//(Left Origin = 6, Top Origin = 67, Usable = 1, Font = Bold)
#define MainVolumeFeedbackSliderControl           1005	//(Left Origin = 15, Top Origin = 134, Width = 128, Height = 15, Usable = 1, Initial Value = 1024, Minimum Value = 0, Maximum Value = 4096, Page Jump Amount = 256, Thumb Bitmap = 1100, Background Bitmap = 1000)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define HelloAlert                                1100
#define HelloOK                                   0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101

//	Resource: PICT 1102
#define BitmapID1102Bitmap                        1102

//	Resource: PICT 1103
#define BitmapID1103Bitmap                        1103


//	Resource: tbmf 1200
#define CloseMouthBitmapFamily                    1200

//	Resource: tbmf 1100
#define OpenMouthBitmapFamily                     1100

//	Resource: tbmf 1000
#define BackBitmapFamily                          1000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

// About form
#define AboutUnnamed1606Button 1300
#define AboutUnnamed1605Label  1301
#define AboutUnnamed1603Label  1302
#define AboutUnnamed1602Label  1303
#define AboutForm 			   1304
