/*******************************************************************
 * 							 Pilot Software
 *
 *		 Copyright(c) 1994, Palm Computing Inc., All Rights Reserved
 *
 *-------------------------------------------------------------------  
 * FileName:
 *		Pilot.h
 *
 * Description:
 *		Include file used by UI library source code modules
 *
 * History:
 *   	6/6/95  RM - Created by Ron Marianetti
 *
 *******************************************************************/  


// This tells "SysAll.h" not to use it's own pre-compiled header
#define	__PILOT_H__ 

#include "Common.h"

// Include the pre-compiled header, if not overriden. This pre-compiled header
//  can be automatically re-generated by CodeWarrior by including the
//  source file "Pilot.pch" in your project.

// The following Mac include file must be included before the Pilot
//  headers for the emulator modules that have both Mac and Pilot
//  code in them
#if EMULATION_LEVEL == EMULATION_MAC
#include <types.h>
#endif


// The following ANSI header files have function declarations used by some
//  of the UI modules.


// Fastest compilation speed is obtained by not including these
//  headers when the pre-compiled header is used.
#ifndef __INCLUDED_PILOT_H_OBJ__
#include <SysAll.h>
#include <UIAll.h>

#define	NON_PORTABLE
#include <Globals.h>
#include <UIGlobals.h>

#endif
