//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 7:06:09 PM on Monday, August 25, 2003
//
//	Generated for file: C:\VMAccConfig\VMAccConfigCW9\Rsc\Resource.frk\VMAccConfig.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"VMConfig"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainNextButton                            1007	//(Left Origin = 120, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCancelButton                          1008	//(Left Origin = 4, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainIncomingServerField                   1009	//(Left Origin = 59, Top Origin = 96, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUsernameField                         1010	//(Left Origin = 59, Top Origin = 18, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainPasswordField                         1011	//(Left Origin = 59, Top Origin = 33, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainEmailAddressField                     1012	//(Left Origin = 59, Top Origin = 53, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainOutgoingServerField                   1013	//(Left Origin = 59, Top Origin = 122, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTitleField                            1014	//(Left Origin = 59, Top Origin = 75, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1001Label                      1001	//(Left Origin = 4, Top Origin = 93, Usable = 1, Font = Bold)
#define MainUsernameLabel                         1002	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define MainUnnamed1003Label                      1003	//(Left Origin = 4, Top Origin = 35, Usable = 1, Font = Bold)
#define MainEmailAddressLabel                     1004	//(Left Origin = 4, Top Origin = 50, Usable = 1, Font = Bold)
#define MainOutgoingServerLabel                   1005	//(Left Origin = 4, Top Origin = 118, Usable = 1, Font = Bold)
#define MainTitleLabel                            1006	//(Left Origin = 4, Top Origin = 77, Usable = 1, Font = Bold)

//	Resource: tFRM 1100
#define SecondForm                                1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SecondNextButton                          1107	//(Left Origin = 120, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SecondBackButton                          1115	//(Left Origin = 4, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SecondServerTypeField                     1109	//(Left Origin = 71, Top Origin = 20, Width = 72, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SecondIncomingPortField                   1110	//(Left Origin = 80, Top Origin = 42, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SecondRootMailboxField                    1112	//(Left Origin = 54, Top Origin = 92, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SecondOutgoingPortField                   1113	//(Left Origin = 87, Top Origin = 60, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SecondReplyToField                        1114	//(Left Origin = 54, Top Origin = 124, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SecondUnnamed1101Label                    1101	//(Left Origin = 4, Top Origin = 22, Usable = 1, Font = Bold)
#define SecondUsernameLabel                       1102	//(Left Origin = 4, Top Origin = 44, Usable = 1, Font = Bold)
#define SecondUnnamed1103Label                    1103	//(Left Origin = 4, Top Origin = 79, Usable = 1, Font = Bold)
#define SecondOutgoingServerLabel                 1105	//(Left Origin = 4, Top Origin = 62, Usable = 1, Font = Bold)
#define SecondTitleLabel                          1106	//(Left Origin = 4, Top Origin = 110, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define ThirdForm                                 1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ThirdNextButton                           1207	//(Left Origin = 120, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ThirdBackButton                           1208	//(Left Origin = 4, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ThirdWirelessServerField                  1209	//(Left Origin = 59, Top Origin = 32, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ThirdAltWirelessServerField               1210	//(Left Origin = 59, Top Origin = 65, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ThirdProxyEmailAddressField               1212	//(Left Origin = 59, Top Origin = 102, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ThirdUnnamed1201Label                     1201	//(Left Origin = 4, Top Origin = 21, Usable = 1, Font = Bold)
#define ThirdAltWirelessServerLabel               1202	//(Left Origin = 4, Top Origin = 57, Usable = 1, Font = Bold)
#define ThirdEmailAddressLabel                    1204	//(Left Origin = 4, Top Origin = 99, Usable = 1, Font = Bold)

//	Resource: tFRM 1300
#define FourthForm                                1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define FourthSaveButton                          1307	//(Left Origin = 120, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FourthBackButton                          1308	//(Left Origin = 4, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FourthAPNField                            1303	//(Left Origin = 59, Top Origin = 22, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define FourthUseEncryptPassField                 1304	//(Left Origin = 59, Top Origin = 50, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define FourthUseSmtpField                        1306	//(Left Origin = 59, Top Origin = 68, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define FourthOutgoingServerLabel                 1301	//(Left Origin = 4, Top Origin = 24, Usable = 1, Font = Bold)
#define FourthTitleLabel                          1302	//(Left Origin = 4, Top Origin = 38, Usable = 1, Font = Bold)
#define FourthUnnamed1305Label                    1305	//(Left Origin = 4, Top Origin = 68, Usable = 1, Font = Bold)


//	Resource: Talt 1100
#define TitleEmptyAlert                           1100
#define TitleEmptyOK                              0

//	Resource: Talt 1000
#define SaveCompleteAlert                         1000
#define SaveCompleteOK                            0


//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

