//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 9:23:56 AM on Tuesday, April 17, 2001
//
//	Generated for file: T:\TRGProd\StarKist\sw\sdk\cw\examples\ExampleJ\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ExampleJ"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainPlayButton                            1001	//(Left Origin = 2, Top Origin = 138, Width = 31, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define MainRecordButton                          1002	//(Left Origin = 78, Top Origin = 138, Width = 46, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define MainProgressSliderControl                 1003	//(Left Origin = 10, Top Origin = 53, Width = 140, Height = 30, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 100, Page Jump Amount = 10, Thumb Bitmap = 1700, Background Bitmap = 1800)
#define MainStopButton                            1004	//(Left Origin = 127, Top Origin = 138, Width = 32, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define MainPauseButton                           1005	//(Left Origin = 37, Top Origin = 138, Width = 37, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Large)
#define MainCardNotFoundLabel                     1006	//(Left Origin = 42, Top Origin = 70, Usable = 1, Font = Bold)
#define MainProgressField                         1007	//(Left Origin = 68, Top Origin = 34, Width = 50, Height = 20, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutTitleLabel                           1102	//(Left Origin = 52, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define AudioExtNotFoundAlert                     1000
#define AudioExtNotFoundOK                        0

//	Resource: Talt 1100
#define VfsExtNotFoundAlert                       1100
#define VfsExtNotFoundOK                          0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutExampleJ                  1000

//	Resource: PICT 1100
#define SmallIconBitmap                           1100
//	Resource: PICT 1000
#define BigIconBitmap                             1000
//	Resource: PICT 1400
#define VGABigIconBitmap                          1400
//	Resource: PICT 1500
#define VGASmallIconBitmap                        1500
//	Resource: PICT 1600
#define VGABigIconInvertedBitmap                  1600
//	Resource: PICT 1700
#define ThumbBitmap                               1700
//	Resource: PICT 1800
#define SliderLineBitmap                          1800
//	Resource: PICT 5896
#define VGASliderLineBitmap                       5896
//	Resource: PICT 5796
#define VGAThumbBitmap                            5796
//	Resource: taif 2002
#define VGABigIconInvertedAppIconFamily           2002

//	Resource: taif 2001
#define VGASmallIconAppIconFamily                 2001

//	Resource: taif 2000
#define VGABigIconAppIconFamily                   2000

//	Resource: taif 1001
#define SmallIconAppIconFamily                    1001

//	Resource: taif 1000
#define BigIconAppIconFamily                      1000
