//	Header generated by Constructor for Palm OS (R) 1.6.2
//
//	Generated at 9:28:02 AM on Wednesday, March 20, 2002
//
//	Generated for file: C:\AS\Software\Hemingway\Sources\SDK\examples\Example D - Key Modifiers\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		""
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainTextInputField                        1001	//(Left Origin = 0, Top Origin = 23, Width = 159, Height = 49, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 3000, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1009GraffitiShift              1009	//(Left Origin = 137, Top Origin = 76)
#define MainUnnamed1002Label                      1002	//(Left Origin = 20, Top Origin = 81, Usable = 1, Font = Bold)
#define MainCapsLockLabel                         1003	//(Left Origin = 33, Top Origin = 111, Usable = 0, Font = Standard)
#define MainLeftShiftLabel                        1004	//(Left Origin = 33, Top Origin = 124, Usable = 1, Font = Standard)
#define MainRightShiftLabel                       1005	//(Left Origin = 33, Top Origin = 137, Usable = 1, Font = Standard)
#define MainControlLabel                          1006	//(Left Origin = 99, Top Origin = 111, Usable = 1, Font = Standard)
#define MainFunctionLabel                         1007	//(Left Origin = 99, Top Origin = 124, Usable = 1, Font = Standard)
#define MainCmdLabel                              1008	//(Left Origin = 99, Top Origin = 137, Usable = 1, Font = Standard)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000


//	Resource: PICT 1000
#define BigIconBitmap                             1000

