//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 4:38:50 PM on Saturday, March 24, 2001
//
//	Generated for file: T:\TRGProd\StarKist\sw\sdk\cw\examples\ExampleG\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ExampleG"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSetTemplateButton                     1001	//(Left Origin = 50, Top Origin = 75, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainResetTemplateButton                   1002	//(Left Origin = 40, Top Origin = 110, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define SilkExtNotFoundAlert                      1000
#define SilkExtNotFoundOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutExampleG                  1000

//	Resource: PICT 1100
#define SmallIconBitmap                           1100
//	Resource: PICT 1000
#define BigIconBitmap                             1000
//	Resource: PICT 1400
#define VGABigIconBitmap                          1400
//	Resource: PICT 1500
#define VGASmallIconBitmap                        1500
//	Resource: PICT 1600
#define Silk1Bitmap                               1600
//	Resource: PICT 1700
#define Silk2Bitmap                               1700
//	Resource: PICT 1800
#define Silk3Bitmap                               1800
//	Resource: PICT 1900
#define Silk4Bitmap                               1900
//	Resource: PICT 2000
#define VGABigIconInvertedBitmap                  2000
//	Resource: tbmf 3000
#define InvertedSilkBitmapFamily                  3000

//	Resource: tbmf 3100
#define NormalSilkBitmapFamily                    3100

//	Resource: taif 2001
#define VGASmallIconAppIconFamily                 2001

//	Resource: taif 2000
#define VGABigIconAppIconFamily                   2000

//	Resource: taif 1001
#define SmallIconAppIconFamily                    1001

//	Resource: taif 1000
#define BigIconAppIconFamily                      1000

//	Resource: taif 2002
#define VGABigIconInvertedAppIconFamily           2002
