//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 8:31:25 AM on Tuesday, November 18, 2003
//
//	Generated for file: FileBrowserForm.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 2000
#define FileBrowserForm                           2000
#define FileBrowserCancelButton                   2001
#define FileBrowserPathField                      2005
#define FileBrowserUnnamed2004Label               2004
#define FileBrowserFileScrollBar                  2006
#define FileBrowserFileTable                      2003


//	Resource: Talt 2001
#define NoDBAlert                                 2001
#define NoDBOK                                    0

//	Resource: Talt 2000
#define NoVolumesAlert                            2000
#define NoVolumesOK                               0


//	Resource: PICT 2018
#define BitmapID2018Bitmap                        2018

//	Resource: PICT 2012
#define BitmapID2012Bitmap                        2012

//	Resource: PICT 2011
#define BitmapID2011Bitmap                        2011

//	Resource: PICT 2002
#define BitmapID2002Bitmap                        2002

//	Resource: PICT 2008
#define BitmapID2008Bitmap                        2008

//	Resource: PICT 2001
#define BitmapID2001Bitmap                        2001

//	Resource: PICT 2021
#define BitmapID2021Bitmap                        2021

//	Resource: PICT 2022
#define BitmapID2022Bitmap                        2022

//	Resource: PICT 2028
#define BitmapID2028Bitmap                        2028

//	Resource: PICT 2019
#define BitmapID2019Bitmap                        2019

//	Resource: PICT 2009
#define BitmapID2009Bitmap                        2009


//	Resource: tbmf 2000
#define FolderBitmapFamily                        2000

//	Resource: tbmf 2010
#define DocumentBitmapFamily                      2010

//	Resource: tbmf 2020
#define CardBitmapFamily                          2020

