//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 12:06:05 PM on Wednesday, September 01, 2004
//
//	Generated for file: MiniMPEG4.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniMPEG4"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainGoButton                              1027	//(Left Origin = 77, Top Origin = 120, Width = 32, Height = 22, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainLoadInMemCheckbox                     1021	//(Left Origin = 2, Top Origin = 105, Width = 54, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainToSDCheckbox                          1023	//(Left Origin = 104, Top Origin = 104, Width = 49, Height = 13, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define MainLoopCheckbox                          1030	//(Left Origin = 59, Top Origin = 105, Width = 44, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define MainInputField                            1003	//(Left Origin = 44, Top Origin = 18, Width = 90, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainOutputField                           1004	//(Left Origin = 44, Top Origin = 30, Width = 90, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainWidthField                            1015	//(Left Origin = 39, Top Origin = 67, Width = 34, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainHeightField                           1016	//(Left Origin = 119, Top Origin = 67, Width = 34, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainSearchRangeField                      1017	//(Left Origin = 21, Top Origin = 79, Width = 50, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainBitRateField                          1018	//(Left Origin = 98, Top Origin = 78, Width = 50, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainKeyFrameField                         1019	//(Left Origin = 21, Top Origin = 91, Width = 50, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainIQuantizationField                    1020	//(Left Origin = 98, Top Origin = 90, Width = 50, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainAverageFPSField                       1022	//(Left Origin = 49, Top Origin = 119, Width = 24, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCurrentFPSField                       1025	//(Left Origin = 49, Top Origin = 131, Width = 24, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainFramesField                           1028	//(Left Origin = 114, Top Origin = 122, Width = 40, Height = 20, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = LED, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainStartColorGadget                      1031	//(Left Origin = 10, Top Origin = 147, Width = 10, Height = 10, Usable = 1)
#define MainEndColorGadget                        1032	//(Left Origin = 140, Top Origin = 147, Width = 10, Height = 10, Usable = 1)
#define MainUnnamed1001Label                      1001	//(Left Origin = 13, Top Origin = 18, Usable = 1, Font = Bold)
#define MainUnnamed1002Label                      1002	//(Left Origin = 2, Top Origin = 31, Usable = 1, Font = Bold)
#define MainUnnamed1009Label                      1009	//(Left Origin = 2, Top Origin = 67, Usable = 1, Font = Bold)
#define MainUnnamed1010Label                      1010	//(Left Origin = 78, Top Origin = 67, Usable = 1, Font = Bold)
#define MainKFLabel                               1011	//(Left Origin = 3, Top Origin = 91, Usable = 1, Font = Bold)
#define MainSRLabel                               1012	//(Left Origin = 2, Top Origin = 79, Usable = 1, Font = Bold)
#define MainBRLabel                               1013	//(Left Origin = 78, Top Origin = 79, Usable = 1, Font = Bold)
#define MainIQLabel                               1014	//(Left Origin = 82, Top Origin = 90, Usable = 1, Font = Bold)
#define MainUnnamed1024Label                      1024	//(Left Origin = 3, Top Origin = 119, Usable = 1, Font = Bold)
#define MainUnnamed1026Label                      1026	//(Left Origin = 5, Top Origin = 131, Usable = 1, Font = Bold)
#define MainFormatList                            1029	//(Left Origin = 93, Top Origin = 48, Width = 60, Usable = 0, Font = Standard, Visible Items = 2)
#define MainQuickPickList                         1034	//(Left Origin = 99, Top Origin = 1, Width = 60, Usable = 0, Font = Standard, Visible Items = 3)
#define MainEncodePushButton                      1007	//(Left Origin = 15, Top Origin = 46, Width = 35, Height = 16, Usable = 0, Group ID = 1, Font = Standard)
#define MainDecodePushButton                      1008	//(Left Origin = 51, Top Origin = 46, Width = 35, Height = 16, Usable = 1, Group ID = 1, Font = Standard)
#define MainOverlayPushButton                     1036	//(Left Origin = 86, Top Origin = 1, Width = 10, Height = 10, Usable = 1, Group ID = 0, Font = Standard)
#define MainFormatPopTrigger                      1006	//(Left Origin = 92, Top Origin = 48, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1029)
#define MainQuickPickPopTrigger                   1033	//(Left Origin = 100, Top Origin = 0, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1034)
#define MainInputGraphicButton                    1005	//(Left Origin = 140, Top Origin = 18, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Bitmap Resource ID = 2000, Selected Bitmap Resource ID = 0)
#define MainGroupID                               1

#define HelpMenu                                  5000
#define AboutForm                                 3001
#define AboutLabel1                               3002
#define AboutLabel2                               3003
#define AboutLabel3                               3004
#define AboutLabel4                               3005
#define AboutLabel5                               3006
#define AboutButton                               3007

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define NoCPMLibAlert                             1000
#define NoCPMLibOK                                0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0

//	Resource: Talt 1200
#define InfoAlert                                 1200
#define InfoOK                                    0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 4001
#define BitmapID4001Bitmap                        4001


//	Resource: tbmf 1000
#define ScreenBitmapFamily                        1000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

