//	Header generated by Constructor for Palm OS (R) 1.6.2
//
//	Generated at 11:18:47 AM on Tuesday, March 19, 2002
//
//	Generated for file: C:\AS\Software\Hemingway\Sources\SDK\examples\Example B\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		""
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainOKButton                              1003	//(Left Origin = 11, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSimpleCheckbox                        1002	//(Left Origin = 97, Top Origin = 139, Width = 62, Height = 13, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainGlobeBitMap                           1000	//(Left Origin = 68, Top Origin = 97, Bitmap Resource ID = 1000, Usable = 1)
#define MainTextInputField                        1001	//(Left Origin = 0, Top Origin = 23, Width = 159, Height = 70, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 3000, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000


//	Resource: PICT 1000
#define BigIconBitmap                             1000

