#ifndef TREO650POWEROUTRSC_H
#define TREO650POWEROUTRSC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 4:27:05 PM on Tuesday, March 07, 2006
//
//	Generated for file: Treo650PowerOut.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Treo650PowerOut"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainPowerOutPowerOnButton                 1001
#define MainPowerOutPowerOffButton                1002


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0


//	Resource: PICT 1218
#define BitmapID1218Bitmap                        1218

//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000


#endif // TREO650POWEROUTRSC_H

#define AboutButton 							  1300
#define AboutLabel1                               1301
#define AboutLabel2    							  1302
#define AboutLabel3 							  1303
#define AboutLabel4 							  1304
#define AboutLabel5 							  1305
#define AboutForm 								  1400

#define MainOptionsMenu 1100
#define MainOptionsAbout 1500