//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 11:54:32 AM on Thursday, March 04, 2004
//
//	Generated for file: MiniImage.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniImage"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainRunButton                             1006	//(Left Origin = 1, Top Origin = 143, Width = 158, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainDisplayButton                         1018	//(Left Origin = 1, Top Origin = 122, Width = 71, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainFitToScreenCheckbox                   1019	//(Left Origin = 77, Top Origin = 123, Width = 83, Height = 14, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainInputField                            1003	//(Left Origin = 44, Top Origin = 44, Width = 100, Height = 11, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainWidthField                            1011	//(Left Origin = 37, Top Origin = 106, Width = 36, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainHeightField                           1012	//(Left Origin = 121, Top Origin = 106, Width = 36, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainOutputField                           1014	//(Left Origin = 43, Top Origin = 58, Width = 100, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1001Label                      1001	//(Left Origin = 10, Top Origin = 44, Usable = 1, Font = Bold)
#define MainUnnamed1002Label                      1002	//(Left Origin = 0, Top Origin = 75, Usable = 1, Font = Bold)
#define MainWidthLabel                            1009	//(Left Origin = 0, Top Origin = 106, Usable = 1, Font = Bold)
#define MainHeightLabel                           1010	//(Left Origin = 81, Top Origin = 106, Usable = 1, Font = Bold)
#define MainUnnamed1013Label                      1013	//(Left Origin = 0, Top Origin = 58, Usable = 1, Font = Bold)
#define MainFileFormatLabel                       1016	//(Left Origin = 9, Top Origin = 90, Usable = 0, Font = Bold)
#define MainColorFormatList                       1020	//(Left Origin = 71, Top Origin = 75, Width = 88, Usable = 0, Font = Standard, Visible Items = 0)
#define MainFileFormatList                        1021	//(Left Origin = 71, Top Origin = 90, Width = 88, Usable = 0, Font = Standard, Visible Items = 0)
#define MainDecodePushButton                      1007	//(Left Origin = 29, Top Origin = 21, Width = 48, Height = 17, Usable = 1, Group ID = 1, Font = Bold)
#define MainEncodePushButton                      1008	//(Left Origin = 78, Top Origin = 21, Width = 48, Height = 17, Usable = 1, Group ID = 1, Font = Bold)
#define MainColorFormatPopTrigger                 1004	//(Left Origin = 70, Top Origin = 74, Width = 88, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1020)
#define MainFileFormatPopTrigger                  1017	//(Left Origin = 70, Top Origin = 89, Width = 88, Height = 12, Usable = 0, Anchor Left = 1, Font = Standard, List ID = 1021)
#define MainInputGraphicButton                    1005	//(Left Origin = 146, Top Origin = 44, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Bitmap Resource ID = 2000, Selected Bitmap Resource ID = 0)
#define MainOutputGraphicButton                   1015	//(Left Origin = 146, Top Origin = 58, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Bitmap Resource ID = 2000, Selected Bitmap Resource ID = 0)
#define MainGroupID                               1

//	Resource: tFRM 1100
#define DisplayForm                               1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)

//	Resource: tFRM 1600
#define AboutForm                                 1600
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1601BitMap                    3000
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603
#define AboutUnnamed1605Label                     1605
#define AboutUnnamed1607Label 					  1607

//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutMiniImage                        1100


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define NoCPMLibAlert                             1000
#define NoCPMLibOK                                0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0

//	Resource: Talt 1200
#define InfoAlert                                 1200
#define InfoOK                                    0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 4001
#define BitmapID4001Bitmap                        4001


//	Resource: tbmf 1000
#define ScreenBitmapFamily                        1000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

