//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 9:13:40 AM on Wednesday, March 12, 2003
//
//	Generated for file: C:\projects\Shelf\SDK\Samples\ExtendedSound\Rsc\MyPlayer.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MyPlayer"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define RecordForm                                1000
#define RecordFileField                           1003
#define RecordTimeField                           1008
#define RecordActualField                         1013
#define RecordBufferField                         1020
#define RecordUnnamed1002Label                    1002
#define RecordUnnamed1007Label                    1007
#define RecordUnnamed1009Label                    1009
#define RecordUnnamed1012Label                    1012
#define RecordUnnamed1014Label                    1014
#define RecordUnnamed1024Label                    1024
#define RecordUnnamed1027Label                    1027
#define RecordLocationList                        1004
#define RecordModeList                            1011
#define RecordEncodingList                        1021
#define RecordSampleTypeList                      1022
#define RecordSampleRateList                      1023
#define RecordFormList                            1025
#define RecordLocationPopTrigger                  1001
#define RecordModePopTrigger                      1010
#define RecordFormPopTrigger                      1015
#define RecordEncodingPopTrigger                  1016
#define RecordSampleTypePopTrigger                1017
#define RecordSampleRatePopTrigger                1018
#define RecordRecordGraphicButton                 1005
#define RecordStopGraphicButton                   1006
#define RecordVolumeFeedbackSliderControl         1019

//	Resource: tFRM 1200
#define PlayForm                                  1200
#define PlayUseSampleRateCheckbox                 1217
#define PlayFileField                             1203
#define PlayTimeField                             1208
#define PlayFileInfoField                         1209
#define PlayActualField                           1213
#define PlayBufferField                           1220
#define PlayUnnamed1201Label                      1201
#define PlayUnnamed1202Label                      1202
#define PlayUnnamed1207Label                      1207
#define PlayUnnamed1212Label                      1212
#define PlayUnnamed1214Label                      1214
#define PlayUnnamed1221Label                      1221
#define PlayUnnamed1224Label                      1224
#define PlayUnnamed1226Label                      1226
#define PlayFormList                              1210
#define PlayLocationList                          1216
#define PlaySampleRateList                        1223
#define PlayFormPopTrigger                        1204
#define PlayLocationPopTrigger                    1211
#define PlaySampleRatePopTrigger                  1218
#define PlayPlayGraphicButton                     1205
#define PlayStopGraphicButton                     1206
#define PlayDeleteGraphicButton                   1215
#define PlayNewGraphicButton                      1225
#define PlayVolumeFeedbackSliderControl           1219

//	Resource: tFRM 1300
#define AboutForm                                 1300
#define AboutUnnamed1306Button                    1306
#define AboutUnnamed1301BitMap                    2700
#define AboutUnnamed1302Label                     1302
#define AboutUnnamed1303Label                     1303
#define AboutUnnamed1304Label                     1304
#define AboutUnnamed1305Label                     1305


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1300
#define PlayErrorAlert                            1300
#define PlayErrorOK                               0

//	Resource: Talt 1200
#define RecordErrorAlert                          1200
#define RecordErrorOK                             0

//	Resource: Talt 1400
#define DeleteFileAlert                           1400
#define DeleteFileOK                              0
#define DeleteFileCancel                          1

//	Resource: Talt 1500
#define NoSampledSoundAlert                       1500
#define NoSampledSoundOK                          0


//	Resource: Talt 1550
#define InformationAlert	                      1550
#define InformationAlertOK                          0


//	Resource: MBAR 1000
#define RecordMenuMenuBar                         1000

//	Resource: MBAR 1200
#define PlayMenuMenuBar                           1200


//	Resource: MENU 1000
#define PlayOptionsMenu                           1000
#define PlayOptionsDelete                         1000
#define PlayOptionsRecord                         1001
#define PlayOptionsAbout                          1111

//	Resource: MENU 1100
#define RecordOptionsMenu                         1100
#define RecordOptionsPlay                         1100
#define RecordOptionsAbout                        1102


//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1301
#define BitmapID1301Bitmap                        1301

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 1401
#define BitmapID1401Bitmap                        1401

//	Resource: PICT 1418
#define BitmapID1418Bitmap                        1418

//	Resource: PICT 1501
#define BitmapID1501Bitmap                        1501

//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1518
#define BitmapID1518Bitmap                        1518

//	Resource: PICT 1601
#define BitmapID1601Bitmap                        1601

//	Resource: PICT 1218
#define BitmapID1218Bitmap                        1218

//	Resource: PICT 1618
#define BitmapID1618Bitmap                        1618

//	Resource: PICT 1701
#define BitmapID1701Bitmap                        1701

//	Resource: PICT 1318
#define BitmapID1318Bitmap                        1318

//	Resource: PICT 1718
#define BitmapID1718Bitmap                        1718

//	Resource: PICT 1801
#define BitmapID1801Bitmap                        1801

//	Resource: PICT 1818
#define BitmapID1818Bitmap                        1818

//	Resource: PICT 1918
#define BitmapID1918Bitmap                        1918

//	Resource: PICT 2001
#define BitmapID2001Bitmap                        2001

//	Resource: PICT 2018
#define BitmapID2018Bitmap                        2018

//	Resource: PICT 2218
#define BitmapID2218Bitmap                        2218

//	Resource: PICT 2201
#define BitmapID2201Bitmap                        2201

//	Resource: PICT 1901
#define BitmapID1901Bitmap                        1901

//	Resource: PICT 2318
#define BitmapID2318Bitmap                        2318

//	Resource: PICT 2301
#define BitmapID2301Bitmap                        2301

//	Resource: PICT 2418
#define BitmapID2418Bitmap                        2418

//	Resource: PICT 2401
#define BitmapID2401Bitmap                        2401

//	Resource: PICT 4001
#define BitmapID4001Bitmap                        4001

//	Resource: PICT 4018
#define BitmapID4018Bitmap                        4018

//	Resource: PICT 4101
#define BitmapID4101Bitmap                        4101

//	Resource: PICT 4118
#define BitmapID4118Bitmap                        4118


//	Resource: tbmf 1300
#define PauseBitmapFamily                         1300

//	Resource: tbmf 1200
#define StopBitmapFamily                          1200

//	Resource: tbmf 1100
#define RecordBitmapFamily                        1100

//	Resource: tbmf 1000
#define PlayBitmapFamily                          1000

//	Resource: tbmf 1400
#define PlaySelectedBitmapFamily                  1400

//	Resource: tbmf 1500
#define RecordSelectedBitmapFamily                1500

//	Resource: tbmf 1600
#define StopSelectedBitmapFamily                  1600

//	Resource: tbmf 1700
#define PauseSelectedBitmapFamily                 1700

//	Resource: tbmf 1800
#define RecycleBinBitmapFamily                    1800

//	Resource: tbmf 1900
#define NewRecordingBitmapFamily                  1900

//	Resource: tbmf 2000
#define SliderBitmapFamily                        2000

//	Resource: tbmf 2200
#define NewSelectedBitmapFamily                   2200

//	Resource: tbmf 2300
#define BinSelectedBitmapFamily                   2300

//	Resource: tbmf 2400
#define RingThumbBitmapFamily                     2400

//	Resource: tbmf 2700
#define AppIconBitmapFamily                       2700


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

#define FrequencyAlert               			  3300
