//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 7:26:24 PM on Sunday, April 24, 2005
//
//	Generated for file: TungstenT5SwitchAudio.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"TungstenT5SwitchAudio"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainSwitchAudioToMultiConnectorButton     1001
#define MainSwitchAudioToSpeakerButton            1002


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define InformationAlert                          1100
#define InformationOK                             0


//	Resource: PICT 1218
#define BitmapID1218Bitmap                        1218

//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

