//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 12:45:02 PM on Thursday, August 21, 2003
//
//	Generated for file: C:\Documents and Settings\prakash ramakrishna\Desktop\VersamailSDK\Device SDK\Samples\AddEmailCW9\Rsc\AddEmailCW9.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"AddEmail"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainExchangeButton                        1002	//(Left Origin = 33, Top Origin = 52, Width = 87, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainHelperButton                          1003	//(Left Origin = 33, Top Origin = 77, Width = 90, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainLaunchButton                          1004	//(Left Origin = 33, Top Origin = 102, Width = 89, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUILaunchButton                        1005	//(Left Origin = 33, Top Origin = 126, Width = 89, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUnnamed1001Label                      1001	//(Left Origin = 31, Top Origin = 27, Usable = 1, Font = Standard)

#define AboutUnnamed1606Button 					  1108
#define AboutUnnamed1605Label 					  1109
#define AboutUnnamed1603Label 					  1110
#define AboutUnnamed1602Label 					  1111
#define HelpAboutAddEmail 						  1112

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define GeneralAlert                              1000
#define GeneralOK                                 0


//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 1012
#define BitmapID1012Bitmap                        1012

//	Resource: PICT 1011
#define BitmapID1011Bitmap                        1011

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002

//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 2006
#define BitmapID2006Bitmap                        2006


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

#define UnsupportedAlert                          1200
