/******************************************************************************
 *
 * File: Starter.h
 *
 * Project : Example J
 *
 *****************************************************************************/
#ifndef _STARTER_H_
#define _STARTER_H_

/***********************************************************************
 *
 *   Constants
 *
 ***********************************************************************/
#define appFileCreator            'Ex_J'
#define appVersionNum              0x01
#define appPrefID                  0x00
#define appPrefVersionNum          0x01

#endif


