//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 3:50:42 PM on Wednesday, April 25, 2001
//
//	Generated for file: T:\TRGProd\StarKist\sw\sdk\cw\examples\ExampleX\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ExampleX"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 57, Top Origin = 58, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define VgaNotFoundAlert                          1000
#define VgaNotFoundOK                             0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsFont                           1000
#define MainOptionsAboutExampleX                  1001

//	Resource: PICT 1200
#define GlobeBitmap                               1200
//	Resource: PICT 1100
#define SmallIconBitmap                           1100
//	Resource: PICT 1000
#define BigIconBitmap                             1000
//	Resource: PICT 1400
#define VGABigIconBitmap                          1400
//	Resource: PICT 1500
#define VGASmallIconBitmap                        1500
//	Resource: PICT 17584
#define VGAGlobeBitmap                            17584
//	Resource: PICT 1600
#define VGABigIconInvertedBitmap                  1600
//	Resource: taif 2002
#define VGABigIconInvertedAppIconFamily           2002

//	Resource: taif 2001
#define VGASmallIconAppIconFamily                 2001

//	Resource: taif 2000
#define VGABigIconAppIconFamily                   2000

//	Resource: taif 1001
#define SmallIconAppIconFamily                    1001

//	Resource: taif 1000
#define BigIconAppIconFamily                      1000
