#ifndef SERIALTRANSRECVRSC_H
#define SERIALTRANSRECVRSC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 4:25:55 PM on Tuesday, March 07, 2006
//
//	Generated for file: SerialTransRecv.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Serial TransRecv"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainSendButton                            1003
#define MainReceiveButton                         1010
#define MainEnableDetectButton                    1011
#define MainPOnButton                             1012
#define MainPOffButton                            1013
#define MainCButton                               1014
#define MainDisableDetectButton                   1015
#define MainSerialOpenButton                      1016
#define MainSerialCloseButton                     1017
#define MainInputField                            1002
#define MainOutputField                           1006
#define MainDebugField                            1008
#define MainInputLabel                            1001
#define MainDebugLabel                            1005
#define MainOutputLabel                           1009
#define MainSerialLabel                           1018
#define MainReceiveLabel                          1019
#define MainBaudRateList                          1007
#define MainBaudRatePopTrigger                    1004

//	Resource: tFRM 1600
#define AboutForm                                 1600
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1601BitMap                    3000
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603
#define AboutUnnamed1605Label                     1605
#define AboutUnnamed1607Label 					  1607
#define AboutUnnamed1608Label				      1608


//	Resource: MENU 1100
#define HelpMenu							      1100
#define HelpAboutSerialCommunication              1100


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define InformationAlert                          1100
#define InformationOK                             0


//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000


#endif // SERIALTRANSRECVRSC_H
