//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 4:46:29 PM on Wednesday, April 04, 2001
//
//	Generated for file: T:\TRGProd\StarKist\sw\sdk\cw\examples\ExampleH\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ExampleH"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainTextField                             1001	//(Left Origin = 70, Top Origin = 146, Width = 60, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainShiftGraffitiShift                    1002	//(Left Origin = 140, Top Origin = 146)
#define MainAppLabel                              1003	//(Left Origin = 4, Top Origin = 18, Usable = 1, Font = Bold)
#define MainAppTable                              1005	//(Left Origin = 8, Top Origin = 30, Width = 141, Height = 110, Editable = 1, Rows = 20)
#define MainAppScrollBar                          1006	//(Left Origin = 152, Top Origin = 29, Width = 7, Height = 112, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)
#define MainAppGadget                             1007	//(Left Origin = 4, Top Origin = 108, Width = 1, Height = 1, Usable = 1)
#define MainHelpButton                            1008	//(Left Origin = 1, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 61, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define LineNumberAlert                           1000
#define LineNumberOK                              0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsFont                           1000
#define MainOptionsAboutExampleH                  1001

//	Resource: tSTR 1000
#define HelpString                                1000	// "This is the help message for ExampleH."

//	Resource: PICT 1100
#define SmallIconBitmap                           1100
//	Resource: PICT 1000
#define BigIconBitmap                             1000
//	Resource: PICT 1400
#define VGABigIconBitmap                          1400
//	Resource: PICT 1500
#define VGASmallIconBitmap                        1500
//	Resource: PICT 1600
#define VGABigIconInvertedBitmap                  1600
//	Resource: taif 2002
#define VGABigIconInvertedAppIconFamily           2002

//	Resource: taif 2001
#define VGASmallIconAppIconFamily                 2001

//	Resource: taif 2000
#define VGABigIconAppIconFamily                   2000

//	Resource: taif 1001
#define SmallIconAppIconFamily                    1001

//	Resource: taif 1000
#define BigIconAppIconFamily                      1000
