//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 1:47:55 PM on Wednesday, September 10, 2003
//
//	Generated for file: C:\Documents and Settings\prakash ramakrishna\Desktop\VersamailSDK\Device SDK\Samples\VersaMailFontApp\Rsc\VMFontApp.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"VMFont"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainDoneButton                            1002
#define MainChangeFontButton                      1003
#define MainTextAreaField                         1001
#define MainFontField                             1006
#define MainFontIDField                           1007
#define MainCheckItOutLabel                       1004
#define MainFontIDTagLabel                        1005
#define MainFontTagLabel                          1009

//	Resource: tFRM 1100
#define AboutForm                                 1100
#define AboutOkButton                             1103
#define AboutUnnamed1101BitMap                    1000
#define AboutUnnamed1102Label                     1102
#define AboutUnnamed1104Label                     1104
#define AboutUnnamed1105Label                     1105

//	Resource: tFRM 1200
#define OptionsForm                               1200
#define OptionsOkButton                           1210
#define OptionsCancelButton                       1211
#define OptionsShowFontStyleCheckbox              1207
#define OptionsShowFontSizeCheckbox               1208
#define OptionsShowFontFaceCheckbox               1209
#define OptionsFontSizeTagLabel                   1201
#define OptionsUnnamed1202Label                   1202
#define OptionsSizeList                           1203
#define OptionsStyleList                          1205
#define OptionsSizePopTrigger                     1204
#define OptionsStylePopTrigger                    1206


//	Resource: Talt 1000
#define LibErrAlert                               1000
#define LibErrOK                                  0


//	Resource: MBAR 1000
#define AboutMenuBar                              1000


//	Resource: MENU 1200
#define EditMenu                                  1200
#define EditOptions                               1200

//	Resource: MENU 1000
#define HelpMenu                                  1000
#define HelpAboutFontoMatic                       1000


//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 2001
#define BitmapID2001Bitmap                        2001

//	Resource: PICT 2008
#define BitmapID2008Bitmap                        2008


//	Resource: tbmf 1000
#define FontoMaticBitmapFamily                    1000


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

