//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 6:19:31 PM on Monday, March 15, 2004
//
//	Generated for file: MiniMP3.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniMP3"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainStartButton                           1001	//(Left Origin = 35, Top Origin = 60, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainStopButton                            1002	//(Left Origin = 34, Top Origin = 97, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainFileButton                            1003	//(Left Origin = 36, Top Origin = 23, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainVolumeFeedbackSliderControl           1005	//(Left Origin = 15, Top Origin = 134, Width = 128, Height = 15, Usable = 1, Initial Value = 1024, Minimum Value = 0, Maximum Value = 2048, Page Jump Amount = 256, Thumb Bitmap = 0, Background Bitmap = 0)

#define AboutUnnamed1606Button                    1200
#define AboutUnnamed1605Label                     1201
#define AboutUnnamed1603Label                     1202
#define AboutUnnamed1602Label                     1203
#define HelpAboutMiniMP3                          1204

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define NoMP3LibAlert                             1000
#define NoMP3LibOK                                0

//	Resource: Talt 1100
#define InfoAlert                                 1100
#define InfoOK                                    0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

