//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 2:44:50 PM on Wednesday, March 21, 2001
//
//	Generated for file: T:\TRGProd\StarKist\sw\sdk\dan\examples\ExampleC\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"ExampleC"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsFont                           1000
#define MainOptionsAboutExampleC                  1001

//	Resource: PICT 1200
#define GlobeBitmap                               1200
//	Resource: PICT 1100
#define SmallIconBitmap                           1100
//	Resource: PICT 1000
#define BigIconBitmap                             1000
//	Resource: taif 1001
#define SmallIconAppIconFamily                    1001

//	Resource: taif 1000
#define BigIconAppIconFamily                      1000
