//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 8:36:27 PM on Monday, March 08, 2004
//
//	Generated for file: MiniGIF.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"MiniGIF"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainFileButton                            1001	//(Left Origin = 36, Top Origin = 27, Width = 93, Height = 36, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define MainDisplayButton                         1002	//(Left Origin = 38, Top Origin = 86, Width = 93, Height = 36, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)

#define AboutUnnamed1606Button 					  1311
#define AboutUnnamed1605Label 					  1310
#define AboutUnnamed1603Label 					  1309
#define AboutUnnamed1602Label 					  1308
#define HelpAboutMiniGIF 						  1302

//	Resource: tFRM 1100
#define LoadingForm                               1100	//(Left Origin = 30, Top Origin = 60, Width = 100, Height = 30, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define LoadingUnnamed1101Label                   1101	//(Left Origin = 25, Top Origin = 8, Usable = 1, Font = Bold 12)

//	Resource: tFRM 1200
#define DisplayForm                               1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define InfoAlert                                 1100
#define InfoOK                                    0


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1011
#define Bitmap2                                   1011

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

