//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 12:04:14 PM on Wednesday, November 05, 2003
//
//	Generated for file: C:\Projects\Shelf\SDK\Samples\IRCommunication\Rsc\IRCOMMTransmitter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"IRCOMM Transmitter"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainSendButton                            1003
#define MainInputField                            1002
#define MainDebugField                            1004
#define MainInputHexField                         1006
#define MainInputLabel                            1001
#define MainDebugLabel                            1005
#define MainInputHexLabel                         1009
#define MainBaudRateList                          1007
#define MainBaudRatePopTrigger                    1008


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define InformationAlert                          1100
#define InformationOK                             0


//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

#define AboutForm                                 1600
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1601BitMap                    3000
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603
#define AboutUnnamed1605Label                     1605
#define AboutUnnamed1607Label 					  1607
#define AboutUnnamed1608Label 					  1608


//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutIRCOMMTransmitter                1100
