//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 6:10:27 PM on Monday, January 03, 2005
//
//	Generated for file: IRCOMMReceiver.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"IRCOMM Receiver"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainReceiveButton                         1003
#define MainOutputField                           1002
#define MainDebugField                            1004
#define MainOutputHexField                        1006
#define MainOutputLabel                           1001
#define MainDebugLabel                            1005
#define MainOutputHexLabel                        1009
#define MainBaudRateList                          1007
#define MainBaudRatePopTrigger                    1008


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0


//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

#define AboutForm                                 1600
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1601BitMap                    3000
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603
#define AboutUnnamed1605Label                     1605
#define AboutUnnamed1607Label 					  1607
#define AboutUnnamed1608Label 					  1608


//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutIRCOMMReceiver                   1100
