//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 7:31:47 PM on Monday, October 06, 2003
//
//	Generated for file: C:\Projects\Shelf\SDK\Samples\IRCommunication\Rsc\IRFramerZire71.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"IR Framer Zire 71"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainSendButton                            1003
#define MainInputField                            1002
#define MainDebugField                            1004
#define MainInputHexField                         1006
#define MainInputLabel                            1001
#define MainDebugLabel                            1005
#define MainInputHexLabel                         1009
#define MainBaudRateList                          1007
#define MainBaudRatePopTrigger                    1008

#define AboutForm                                 1600
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603
#define AboutUnnamed1605Label                     1605
#define AboutUnnamed1607Label                     1607
#define HelpAboutIRFramerZire71     			  2000


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0


//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

