//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 6:34:55 PM on Wednesday, September 10, 2003
//
//	Generated for file: C:\Projects\Shelf\Applications\IRUnframer\Rsc\IRReceiverRaw.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Raw IR Receiver"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainReceiveButton                         1003
#define MainOutputField                           1002
#define MainDebugField                            1004
#define MainOutputHexField                        1006
#define MainOutputLabel                           1001
#define MainDebugLabel                            1005
#define MainOutputHexLabel                        1009
#define MainBaudRateList                          1007
#define MainBaudRatePopTrigger                    1008

#define AboutForm                                 1600
#define AboutUnnamed1605Label                     1605
#define AboutUnnamed1606Button                    1606
#define AboutUnnamed1607Label                     1607
#define AboutUnnamed1602Label                     1602
#define AboutUnnamed1603Label                     1603


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0


//	Resource: PICT 1218
#define BitmapID1218Bitmap                        1218

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

#define HelpAboutRawIRReceiver					  2000
