//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 2:58:44 PM on Tuesday, May 10, 2005
//
//	Generated for file: TungstenT5FlowControl.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"TungstenT5FlowControl"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainDisableFlowControlButton              1001
#define MainEnableFlowControlButton               1002


//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0


//	Resource: PICT 1218
#define BitmapID1218Bitmap                        1218

//	Resource: PICT 1118
#define BitmapID1118Bitmap                        1118

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101


//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

#define AboutButton 							  1300
#define AboutLabel1                               1301
#define AboutLabel2    							  1302
#define AboutLabel3 							  1303
#define AboutLabel4 							  1304
#define AboutLabel5 							  1305
#define AboutForm 								  1400

#define HelpMenu 								  1100