//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 5:53:32 PM on Friday, March 14, 2003
//
//	Generated for file: E:\Palm\Samples\FullScreenWriting\Rsc\GoLCDTest.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"GoLCD Test"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainTestButton                            1014	//(Left Origin = 122, Top Origin = 146, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainApplyButton                           1020	//(Left Origin = 116, Top Origin = 109, Width = 36, Height = 26, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainInvertCheckbox                        1021	//(Left Origin = 101, Top Origin = 59, Width = 45, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define MainWidthField                            1016	//(Left Origin = 78, Top Origin = 108, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainHeightField                           1017	//(Left Origin = 78, Top Origin = 124, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainXField                                1018	//(Left Origin = 13, Top Origin = 108, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainYField                                1019	//(Left Origin = 14, Top Origin = 123, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainTimeoutField                          1023	//(Left Origin = 48, Top Origin = 147, Width = 30, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainInkColorGadget                        1006	//(Left Origin = 53, Top Origin = 59, Width = 40, Height = 12, Usable = 1)
#define MainGsiColorGadget                        1008	//(Left Origin = 53, Top Origin = 74, Width = 40, Height = 12, Usable = 1)
#define MainGSIGraffitiShift                      1005	//(Left Origin = 104, Top Origin = 148)
#define MainUnnamed1003Label                      1003	//(Left Origin = 0, Top Origin = 19, Usable = 1, Font = Bold)
#define MainUnnamed1004Label                      1004	//(Left Origin = 0, Top Origin = 60, Usable = 1, Font = Bold)
#define MainUnnamed1007Label                      1007	//(Left Origin = 0, Top Origin = 75, Usable = 1, Font = Bold)
#define MainUnnamed1009Label                      1009	//(Left Origin = 0, Top Origin = 93, Usable = 1, Font = Bold)
#define MainUnnamed1010Label                      1010	//(Left Origin = 4, Top Origin = 109, Usable = 1, Font = Standard)
#define MainUnnamed1011Label                      1011	//(Left Origin = 4, Top Origin = 124, Usable = 1, Font = Standard)
#define MainUnnamed1012Label                      1012	//(Left Origin = 51, Top Origin = 110, Usable = 1, Font = Standard)
#define MainUnnamed1013Label                      1013	//(Left Origin = 0, Top Origin = 147, Usable = 1, Font = Bold)
#define MainUnnamed1015Label                      1015	//(Left Origin = 48, Top Origin = 125, Usable = 1, Font = Standard)
#define MainEnablePushButton                      1001	//(Left Origin = 58, Top Origin = 35, Width = 45, Height = 16, Usable = 1, Group ID = 1, Font = Bold 12)
#define MainDisablePushButton                     1002	//(Left Origin = 104, Top Origin = 35, Width = 45, Height = 16, Usable = 1, Group ID = 1, Font = Bold 12)
#define MainOffPushButton                         1024	//(Left Origin = 12, Top Origin = 35, Width = 45, Height = 16, Usable = 1, Group ID = 1, Font = Bold 12)
#define MainScrollUpRepeating                     1025	//(Left Origin = 80, Top Origin = 144, Width = 13, Height = 8, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainScrollDownRepeating                   1026	//(Left Origin = 80, Top Origin = 152, Width = 13, Height = 8, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainGroupID                               1

//	Resource: tFRM 1100
#define TestForm                                  1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TestUnnamed1101Button                     1101	//(Left Origin = 62, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define TestTestField                             1103	//(Left Origin = 54, Top Origin = 62, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define TestUnnamed1102GraffitiShift              1102	//(Left Origin = 150, Top Origin = 149)

//	Resource: tFRM 1200
#define DoAStrokeForm                             1200	//(Left Origin = 2, Top Origin = 18, Width = 156, Height = 140, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DoAStrokeOKButton                         1203	//(Left Origin = 62, Top Origin = 119, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DoAStrokeUnnamed1201GraffitiShift         1201	//(Left Origin = 127, Top Origin = 121)
#define DoAStrokeUnnamed1202Label                 1202	//(Left Origin = 6, Top Origin = 19, Usable = 1, Font = Bold)

//	Resource: tFRM 1300
#define AboutForm                                 1300	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutUnnamed1306Button                    1306	//(Left Origin = 62, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1301BitMap                    1000	//(Left Origin = 30, Top Origin = 21, Bitmap Resource ID = 1000, Usable = 1)
#define AboutUnnamed1302Label                     1302	//(Left Origin = 58, Top Origin = 24, Usable = 1, Font = Bold 12)
#define AboutUnnamed1303Label                     1303	//(Left Origin = 81, Top Origin = 40, Usable = 1, Font = Standard)
#define AboutUnnamed1304Label                     1304	//(Left Origin = 28, Top Origin = 108, Usable = 1, Font = Standard)
#define AboutUnnamed1305Label                     1305	//(Left Origin = 22, Top Origin = 61, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define NotAvailableAlert                         1100
#define NotAvailableOK                            0

//	Resource: Talt 1200
#define DoAStrokeAlert                            1200
#define DoAStrokeOK                               0


//	Resource: MBAR 1000
#define OptionsMenuBar                            1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAbout                              1000	//  Command Key: A


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1008
#define Bitmap2                                   1008

//	Resource: PICT 1011
#define Bitmap3                                   1011

//	Resource: PICT 1012
#define Bitmap4                                   1012


//	Resource: tbmf 1000
#define IconBitmapFamily                          1000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

